import type { Balde } from './tipos';

export const BALDES: { chave: Balde; rotulo: string }[] = [
  { chave: 'para_fazer', rotulo: 'Para fazer' },
  { chave: 'hoje', rotulo: 'Vence hoje' },
  { chave: 'amanha', rotulo: 'Amanhã' },
  { chave: 'atrasadas', rotulo: 'Atrasadas' },
  { chave: 'semana', rotulo: 'Esta semana' },
  { chave: 'proxima_semana', rotulo: 'Semana que vem' },
  { chave: 'concluidas', rotulo: 'Concluídas' },
];

export const TEXTOS_DE_TAREFAS = {
  titulo: 'Tarefas',
  novaTarefa: 'Nova tarefa',
  agendarTarefa: 'Agendar tarefa',
  editarTarefa: 'Editar tarefa',
  tipoDeTarefa: 'Tipo de tarefa',
  tituloDaTarefa: 'Título da tarefa',
  prioridade: 'Prioridade',
  duracao: 'Duração',
  corretorResponsavel: 'Corretor responsável',
  vincular: 'Vincular a tarefa',
  contato: 'Contato',
  imovel: 'Imóvel',
  atendimento: 'Atendimento',
  tirarImovel: 'Tirar o imóvel',
  trocarImovel: 'Trocar imóvel',
  prioridadeAlta: 'Prioridade alta',
  buscarImovel: 'Buscar por título ou código',
  nenhumImovel: 'Nenhum imóvel encontrado.',
  observacao: 'Observação',
  observacaoDica: 'Só a equipe vê. Nunca vai para o lead.',
  marcarConcluida: 'Marcar como concluída',
  semTarefasNoDia: 'Sem tarefas para o dia',
  agendaDe: 'Agenda de',
  agendaDaEquipe: 'Agenda da equipe',
  diaAnterior: 'Dia anterior',
  proximoDia: 'Próximo dia',
  visita: 'Visita',
  semCategoriasCadastradas: 'Nenhuma categoria. Cadastre em Minha imobiliária › Listas.',
  categoria: 'Categoria',
  semCategoria: 'Sem categoria',
  tituloDoCampo: 'O que fazer',
  exemploDeTitulo: 'Ex.: ligar pra confirmar a visita',
  data: 'Data',
  hora: 'Hora',
  responsavel: 'Responsável',
  responsavelDoLead: 'Responsável do lead',
  manterResponsavel: 'Manter o responsável atual',
  trocar: 'Trocar',
  descricao: 'Detalhes (opcional)',
  salvar: 'Salvar',
  criar: 'Criar tarefa',
  cancelar: 'Cancelar',
  concluir: 'Concluir',
  reabrir: 'Reabrir',
  editar: 'Editar',
  excluir: 'Excluir',
  atrasada: 'Atrasada',
  semAbertas: 'Nenhuma tarefa aberta.',
  concluidas: 'Concluídas',
  criada: 'Tarefa criada.',
  salva: 'Tarefa salva.',
  concluida: 'Tarefa concluída.',
  reaberta: 'Tarefa reaberta.',
  excluida: 'Tarefa excluída.',
  erro: 'Não deu certo. Tente de novo.',
  faltaTitulo: 'Escreva o que é pra fazer.',
  faltaData: 'Escolha a data.',
  faltaHora: 'Escolha a hora.',
  faltaLead: 'Escolha o lead.',
  proxima: 'Criar a próxima tarefa deste lead?',
  agoraNao: 'Agora não',
  perguntaExcluir: 'Excluir esta tarefa?',
  perguntaExcluirDescricao: 'Ela some do card e das Atividades. Não tem volta.',
  semCard: 'Pra criar tarefa, coloque o lead no funil.',
  semCardAtividades: 'Esse lead ainda não está no funil. Coloque ele no funil pela conversa ou pelo card e crie a tarefa de novo.',
  lead: 'Lead',
  buscarLead: 'Buscar por nome ou telefone',
} as const;

export const PRIORIDADES: { valor: 'low' | 'medium' | 'high'; rotulo: string }[] = [
  { valor: 'low', rotulo: 'Baixa' },
  { valor: 'medium', rotulo: 'Média' },
  { valor: 'high', rotulo: 'Alta' },
];

/** Duração da tarefa, em minutos (o servidor aceita de 15 a 480). */
export const DURACOES_DA_TAREFA = [15, 30, 45, 60, 90, 120, 180, 240] as const;
